In [ ]:
#import statements
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Data Overview

In [ ]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("/content/drive/MyDrive/combined_data.csv", low_memory=False, na_values=['', ' '])
df.shape

In [ ]:
df.head()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,212012996,1102,NaN,FRAUD - FALSE PRETENSE / SCHEME,B2,259,0,2020-01-01 00:00:00,2020,1,Wednesday,0,NaN,ALEXANDER ST,42.316942,-71.069912,"(42.3169424347871, -71.0699121273113)"
1,212008096,1107,NaN,FRAUD - IMPERSONATION,A1,118,0,2020-01-01 00:00:00,2020,1,Wednesday,0,NaN,BOYLSTON ST,42.352418,-71.065255,"(42.3524181472861, -71.0652549858121)"
2,202000034,3006,NaN,SICK/INJURED/MEDICAL - PERSON,C6,201,0,2020-01-01 00:00:00,2020,1,Wednesday,0,NaN,W BROADWAY,42.340070,-71.052794,"(42.340069862647, -71.0527942008028)"
3,202007210,1001,NaN,FORGERY / COUNTERFEITING,C6,200,0,2020-01-01 00:00:00,2020,1,Wednesday,0,NaN,ORTON-MAROTTA WAY,42.341288,-71.054679,"(42.3412875043904, -71.054679326494)"
4,202000355,617,NaN,LARCENY THEFT FROM BUILDING,A1,77,0,2020-01-01 00:00:00,2020,1,Wednesday,0,NaN,FRIEND ST,42.361839,-71.059765,"(42.3618385665647, -71.0597648909416)"

In [ ]:
df.describe()

,OFFENSE_CODE,OFFENSE_CODE_GROUP,SHOOTING,YEAR,MONTH,HOUR,UCR_PART,Lat,Long
count,433825.000000,0.0,433825.000000,433825.000000,433825.000000,433825.000000,0.0,4.112140e+05,4.112140e+05
mean,2350.568195,NaN,0.009935,2022.469062,6.426289,12.644912,NaN,4.232296e+01,-7.108351e+01
std,1192.202433,NaN,0.099178,1.660890,3.328813,6.481940,NaN,7.345040e-02,1.152090e-01
min,111.000000,NaN,0.000000,2020.000000,1.000000,0.000000,NaN,1.327276e-07,-7.134947e+01
25%,1102.000000,NaN,0.000000,2021.000000,4.000000,9.000000,NaN,4.229755e+01,-7.109891e+01
50%,3005.000000,NaN,0.000000,2023.000000,6.000000,13.000000,NaN,4.232866e+01,-7.107754e+01
75%,3201.000000,NaN,0.000000,2024.000000,9.000000,18.000000,NaN,4.234893e+01,-7.106096e+01
max,99999.000000,NaN,1.000000,2025.000000,12.000000,23.000000,NaN,4.246141e+01,5.249691e-08

In [ ]:
df.dtypes

INCIDENT_NUMBER         object
OFFENSE_CODE             int64
OFFENSE_CODE_GROUP     float64
OFFENSE_DESCRIPTION     object
DISTRICT                object
REPORTING_AREA          object
SHOOTING                 int64
OCCURRED_ON_DATE        object
YEAR                     int64
MONTH                    int64
DAY_OF_WEEK             object
HOUR                     int64
UCR_PART               float64
STREET                  object
Lat                    float64
Long                   float64
Location                object
dtype: object

In [ ]:
missing_counts = df.isna().sum()

print("Missing values per column:")
print(missing_counts)

Missing values per column:
INCIDENT_NUMBER             0
OFFENSE_CODE                0
OFFENSE_CODE_GROUP     433825
OFFENSE_DESCRIPTION         0
DISTRICT                 1879
REPORTING_AREA         100787
SHOOTING                    0
OCCURRED_ON_DATE            0
YEAR                        0
MONTH                       0
DAY_OF_WEEK                 0
HOUR                        0
UCR_PART               433825
STREET                    681
Lat                     22611
Long                    22611
Location                22611
dtype: int64

In [ ]:
df_month = df.dropna(subset=['YEAR', 'MONTH'])

# Ensure 'OCCURRED_ON_DATE' is in datetime format and set to the start of the month
df_month['OCCURRED_ON_DATE'] = pd.to_datetime(df_month['OCCURRED_ON_DATE'], errors='coerce').dt.to_period('M').dt.to_timestamp()

# Group by Year and Month and count incidents
monthly = df_month.groupby(['YEAR', 'MONTH']).size().reset_index(name='Incidents')

# Create a YearMonth column for plotting
monthly['YearMonth'] = pd.to_datetime(monthly['YEAR'].astype(str) + '-' + monthly['MONTH'].astype(str) + '-01')

# Ensure the data only goes up to September 2025 (as per previous analysis)
monthly = monthly[monthly['YearMonth'] <= "2025-09-01"]

# --- Plot ---
plt.figure(figsize=(14,6))
plt.plot(monthly['YearMonth'], monthly['Incidents'], marker='o', color="firebrick")

plt.title("Monthly Crime Incidents in Boston (2020–Sep 2025) With Uncleaned Dataset", fontsize=20)
plt.xlabel("Month", fontsize=15)  # Increased font size
plt.ylabel("Number of Incidents", fontsize=20) # Increased font size
plt.grid(alpha=0.3)

# Format x-axis to show months
plt.gca().xaxis.set_major_locator(mdates.MonthLocator(interval=3))
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))  # e.g., Jan 2024

plt.xticks(rotation=45, ha='right', fontsize=15) # Increased font size for ticks
plt.yticks(fontsize=20) # Increased font size for ticks
plt.tight_layout()
plt.savefig("monthly_incidents.eps", format="eps", dpi=300, bbox_inches="tight")
plt.show()

# Data Preprocessing and Cleaning

In [ ]:
# Drop OFFENSE_CODE_GROUP and UCR_PART columns (empty columns)
cols_to_drop = ["OFFENSE_CODE_GROUP", "UCR_PART"]
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns], errors="ignore")

# Drop rows with missing location information
df = df.dropna(subset=["Location", "DISTRICT"])

# df is now your cleaned dataset
print(f"Cleaned dataset loaded into df, shape = {df.shape}")

Cleaned dataset loaded into df, shape = (410002, 15)

In [ ]:
counts_by_year = df['YEAR'].value_counts().sort_index()
total_count = counts_by_year.sum()

print(counts_by_year)
print("\nTotal incidents:", total_count)

YEAR
2020    68928
2021    67983
2022    70008
2023    72588
2024    74625
2025    55870
Name: count, dtype: int64

Total incidents: 410002

In [ ]:
# Count the number of incidents for each offense description
offense_counts = df['OFFENSE_DESCRIPTION'].value_counts()

# Display the counts
print("Number of incidents per offense description:")
print(offense_counts.head(20))

Number of incidents per offense description:
OFFENSE_DESCRIPTION
INVESTIGATE PERSON                              39418
SICK ASSIST                                     32096
M/V - LEAVING SCENE - PROPERTY DAMAGE           24038
INVESTIGATE PROPERTY                            18996
TOWED MOTOR VEHICLE                             17634
VANDALISM                                       16399
ASSAULT - SIMPLE                                16280
LARCENY SHOPLIFTING                             15774
PROPERTY - LOST/ MISSING                        12193
LARCENY THEFT FROM MV - NON-ACCESSORY           11163
M/V ACCIDENT - PROPERTY DAMAGE                  10285
VERBAL DISPUTE                                   9889
DRUGS - POSSESSION/ SALE/ MANUFACTURING/ USE     9738
LARCENY THEFT FROM BUILDING                      9560
THREATS TO DO BODILY HARM                        9468
ASSAULT - AGGRAVATED                             8859
SICK/INJURED/MEDICAL - PERSON                    8553
LARCENY ALL OTHERS                               8298
M/V ACCIDENT - OTHER                             7989
HARASSMENT/ CRIMINAL HARASSMENT                  6275
Name: count, dtype: int64

In [ ]:
# List of offense descriptions to drop (unlikely to spillover)
drop_offenses = [
    "SICK ASSIST",
    "SICK/INJURED/MEDICAL - PERSON",
    "TOWED MOTOR VEHICLE",
    "INVESTIGATE PERSON",
    "INVESTIGATE PROPERTY"
]

# drop from df
df = df[~df["OFFENSE_DESCRIPTION"].isin(drop_offenses)].copy()

offense_counts = df['OFFENSE_DESCRIPTION'].value_counts()
print(offense_counts)
print(df.shape)

OFFENSE_DESCRIPTION
M/V - LEAVING SCENE - PROPERTY DAMAGE    24038
VANDALISM                                16399
ASSAULT - SIMPLE                         16280
LARCENY SHOPLIFTING                      15774
PROPERTY - LOST/ MISSING                 12193
                                         ...
Justifiable Homicide                         2
PROSTITUTION - ASSISTING OR PROMOTING        2
Evidence Tracker Incidents                   1
MANSLAUGHTER - NEGLIGENCE                    1
PRISONER ESCAPE / ESCAPE & RECAPTURE         1
Name: count, Length: 122, dtype: int64
(293305, 15)

In [ ]:
missing_counts = df.isna().sum()

print("Missing values per column:")
print(missing_counts)

Missing values per column:
INCIDENT_NUMBER            0
OFFENSE_CODE               0
OFFENSE_DESCRIPTION        0
DISTRICT                   0
REPORTING_AREA         66536
SHOOTING                   0
OCCURRED_ON_DATE           0
YEAR                       0
MONTH                      0
DAY_OF_WEEK                0
HOUR                       0
STREET                   516
Lat                        0
Long                       0
Location                   0
dtype: int64

In [ ]:
df_month = df.dropna(subset=['YEAR', 'MONTH'])

# Ensure 'OCCURRED_ON_DATE' is in datetime format and set to the start of the month
df_month['OCCURRED_ON_DATE'] = pd.to_datetime(df_month['OCCURRED_ON_DATE'], errors='coerce').dt.to_period('M').dt.to_timestamp()

# Group by Year and Month and count incidents
monthly = df_month.groupby(['YEAR', 'MONTH']).size().reset_index(name='Incidents')

# Create a YearMonth column for plotting
monthly['YearMonth'] = pd.to_datetime(monthly['YEAR'].astype(str) + '-' + monthly['MONTH'].astype(str) + '-01')

# Ensure the data only goes up to September 2025 (as per previous analysis)
monthly = monthly[monthly['YearMonth'] <= "2025-09-01"]

# --- Plot ---
plt.figure(figsize=(14,6))
plt.plot(monthly['YearMonth'], monthly['Incidents'], marker='o', color="firebrick")

plt.title("Monthly Crime Incidents in Boston (2020–Sep 2025) With Cleaned Dataset", fontsize=20)
plt.xlabel("Month", fontsize=15)  # Increased font size
plt.ylabel("Number of Incidents", fontsize=20) # Increased font size
plt.grid(alpha=0.3)

# Format x-axis to show months
plt.gca().xaxis.set_major_locator(mdates.MonthLocator(interval=3))
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))  # e.g., Jan 2024

plt.xticks(rotation=45, ha='right', fontsize=15) # Increased font size for ticks
plt.yticks(fontsize=20) # Increased font size for ticks
plt.tight_layout()
plt.show()
plt.savefig("monthly_incidents.png")

In [ ]:
print(df['YEAR'].min(), df['YEAR'].max())

2020 2025

# Data Transformation

In [ ]:
def parse_dates_multi_utc(col: pd.Series) -> pd.Series:
    s = col.astype(str).str.strip()
    s = (s.str.replace(r"[…]|\.{3}", "", regex=True)
           .str.replace(r"\s+", " ", regex=True))

    # parse with utc=True every time so results are homogeneous tz-aware
    parsed = pd.to_datetime(s, format="%Y-%m-%d", errors="coerce", utc=True)

    for fmt in [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %I:%M %p",
        "%m/%d/%Y",
        "%m/%d/%Y %H:%M",
        "%m/%d/%Y %H:%M:%S",
    ]:
        mask = parsed.isna()
        if mask.any():
            parsed.loc[mask] = pd.to_datetime(s[mask], format=fmt, errors="coerce", utc=True)

    # final fallback (dateutil)
    mask = parsed.isna()
    if mask.any():
        parsed.loc[mask] = pd.to_datetime(s[mask], errors="coerce", utc=True)

    return parsed  # dtype should be datetime64[ns, UTC]

df = df.copy()
df['OCCURRED_ON_DATE'] = parse_dates_multi_utc(df['OCCURRED_ON_DATE'])

#  standardize all to UTC and strip time zone info
df['OCCURRED_ON_DATE'] = df['OCCURRED_ON_DATE'].dt.tz_convert('UTC').dt.tz_localize(None)

# compute t since global t0 (in days)
t0 = df['OCCURRED_ON_DATE'].min()
df['t'] = (df['OCCURRED_ON_DATE'] - t0).dt.total_seconds() / 86400.0

# build the nested list
times_by_district = (
    df.dropna(subset=['DISTRICT', 't'])
      .sort_values('t')
      .groupby('DISTRICT')['t']
      .apply(list)
      .to_dict()
)
districts = sorted(times_by_district.keys())
nested_list = [times_by_district[d] for d in districts]
print(districts)

['A1', 'A15', 'A7', 'B2', 'B3', 'C11', 'C6', 'D14', 'D4', 'E13', 'E18', 'E5', 'External', 'Outside of']

In [ ]:
#Roxbury B2, Mattapan B3
import json

df = df.copy()
df['OCCURRED_ON_DATE'] = parse_dates_multi_utc(df['OCCURRED_ON_DATE'])

#  standardize all to UTC and strip time zone info
df['OCCURRED_ON_DATE'] = df['OCCURRED_ON_DATE'].dt.tz_convert('UTC').dt.tz_localize(None)

cutoff = pd.Timestamp('2025-04-01')
df_recent = df[df['OCCURRED_ON_DATE'] >= cutoff].copy()

# recompute t0 and derived values using only recent data
t0 = df_recent['OCCURRED_ON_DATE'].min()
df_recent['t'] = (df_recent['OCCURRED_ON_DATE'] - t0).dt.total_seconds() / 86400.0

# rebuild nested list by district
times_by_district = (
    df_recent.dropna(subset=['DISTRICT', 't'])
             .sort_values('t')
             .groupby('DISTRICT')['t']
             .apply(list)
             .to_dict()
)

districts = sorted(times_by_district.keys())
#print(districts)
nested_list = [times_by_district[d] for d in districts]

#print(df_recent['OCCURRED_ON_DATE'].min(), df_recent['OCCURRED_ON_DATE'].max())
print(nested_list[3])
print(nested_list[4])

print(np.max(np.array(nested_list[3])), np.max(np.array(nested_list[4])))

with open("data.jsonl", "w") as f:
    json.dump(nested_list[3], f)
    f.write("\n")
    json.dump(nested_list[4], f)
    f.write("\n")

[0.0, 0.0, 0.0, 0.0, 0.03125, 0.2743055555555556, 0.3472222222222222, 0.40555555555555556, 0.4222222222222222, 0.4222222222222222, 0.5263888888888889, 0.5395833333333333, 0.5819444444444445, 0.6041666666666666, 0.6229166666666667, 0.6388888888888888, 0.65625, 0.6597222222222222, 0.6611111111111111, 0.6784722222222223, 0.6819444444444445, 0.6979166666666666, 0.7916666666666666, 0.8055555555555556, 0.81875, 0.8638888888888889, 0.8798611111111111, 0.9138888888888889, 0.9138888888888889, 1.0, 1.0, 1.2569444444444444, 1.2604166666666667, 1.3083333333333333, 1.4055555555555554, 1.4159722222222222, 1.4805555555555556, 1.5541666666666667, 1.5541666666666667, 1.625, 1.6465277777777778, 1.66875, 1.6715277777777777, 1.6979166666666667, 1.7104166666666667, 1.8243055555555556, 1.9166666666666667, 1.917361111111111, 2.0, 2.0, 2.0, 2.0, 2.0395833333333333, 2.097916666666667, 2.3520833333333333, 2.3541666666666665, 2.4402777777777778, 2.584722222222222, 2.6194444444444445, 2.6354166666666665, 2.716666666666667, 2.8333333333333335, 2.8673611111111112, 2.9305555555555554, 2.9993055555555554, 3.0, 3.0, 3.2527777777777778, 3.4770833333333333, 3.60625, 3.654861111111111, 3.6694444444444443, 3.6770833333333335, 3.686111111111111, 3.7465277777777777, 3.772222222222222, 4.0, 4.059722222222222, 4.1715277777777775, 4.280555555555556, 4.366666666666666, 4.392361111111111, 4.416666666666667, 4.447916666666667, 4.4625, 4.476388888888889, 4.479166666666667, 4.569444444444445, 4.645833333333333, 4.645833333333333, 4.778472222222222, 4.78125, 4.807638888888889, 4.81875, 4.839583333333334, 4.936111111111111, 5.021527777777778, 5.060416666666667, 5.148611111111111, 5.444444444444445, 5.447916666666667, 5.478472222222222, 5.5, 5.5, 5.669444444444444, 5.680555555555555, 5.701388888888889, 5.722916666666666, 5.75, 5.8909722222222225, 5.897222222222222, 6.0, 6.0, 6.127083333333333, 6.291666666666667, 6.302083333333333, 6.425, 6.434722222222222, 6.438888888888889, 6.46875, 6.498611111111111, 6.5375, 6.538888888888889, 6.730555555555555, 6.735416666666667, 6.929861111111111, 6.98125, 7.0, 7.0, 7.0, 7.298611111111111, 7.3597222222222225, 7.447916666666667, 7.520833333333333, 7.573611111111111, 7.589583333333334, 7.607638888888889, 7.725, 7.778472222222222, 7.935416666666667, 7.955555555555556, 8.0, 8.0, 8.180555555555555, 8.334027777777777, 8.404166666666667, 8.503472222222221, 8.5625, 8.570833333333333, 8.583333333333334, 8.63125, 8.652777777777779, 8.655555555555555, 8.663194444444445, 8.697222222222223, 8.719444444444445, 8.722916666666666, 8.747222222222222, 8.814583333333333, 8.820833333333333, 8.822916666666666, 8.846527777777778, 8.89375, 9.28125, 9.291666666666666, 9.354166666666666, 9.388194444444444, 9.395833333333334, 9.41388888888889, 9.5, 9.527777777777779, 9.594444444444445, 9.597222222222221, 9.645833333333334, 9.666666666666666, 9.677083333333334, 9.720833333333333, 9.73611111111111, 9.753472222222221, 9.76388888888889, 9.791666666666666, 9.85763888888889, 9.9, 9.90625, 9.931944444444444, 9.958333333333334, 10.0, 10.0, 10.0, 10.296527777777778, 10.39861111111111, 10.409027777777778, 10.430555555555555, 10.55486111111111, 10.569444444444445, 10.583333333333334, 10.595138888888888, 10.597222222222221, 10.604166666666666, 10.61736111111111, 10.634722222222223, 10.700694444444444, 10.70138888888889, 10.708333333333334, 10.784722222222221, 10.879861111111111, 10.950694444444444, 10.978472222222223, 10.995833333333334, 11.0, 11.0, 11.002083333333333, 11.015972222222222, 11.029861111111112, 11.106944444444444, 11.25, 11.339583333333334, 11.421527777777778, 11.567361111111111, 11.604166666666666, 11.638194444444444, 11.680555555555555, 11.713888888888889, 11.765972222222222, 12.0, 12.0, 12.0, 12.354166666666666, 12.375, 12.58125, 12.58125, 12.63888888888889, 12.6875, 12.689583333333333, 12.738888888888889, 12.752777777777778, 12.754861111111111, 12.75625, 12.833333333333334, 12.916666666666666, 12.969444444444445, 13.0, 13.0, 13.0, 13.161805555555556, 13.248611111111112, 13.333333333333334, 13.372916666666667, 13.395138888888889, 13.410416666666666, 13.44375, 13.44513888888889, 13.583333333333334, 13.665972222222223, 13.729166666666666, 13.747222222222222, 13.833333333333334, 13.836805555555555, 13.865277777777777, 13.877777777777778, 13.879166666666666, 13.92013888888889, 13.971527777777778, 14.0, 14.288194444444445, 14.338888888888889, 14.34375, 14.510416666666666, 14.543055555555556, 14.60625, 14.694444444444445, 14.697222222222223, 14.745138888888889, 14.752083333333333, 14.7625, 15.0, 15.01388888888889, 15.136805555555556, 15.395138888888889, 15.40625, 15.42986111111111, 15.484027777777778, 15.583333333333334, 15.660416666666666, 15.680555555555555, 15.689583333333333, 15.8, 15.958333333333334, 15.959722222222222, 16.0, 16.0, 16.041666666666668, 16.138194444444444, 16.333333333333332, 16.414583333333333, 16.48263888888889, 16.524305555555557, 16.528472222222224, 16.65625, 16.67222222222222, 16.69097222222222, 16.729166666666668, 16.73125, 16.74652777777778, 16.75, 16.79652777777778, 16.875, 16.875, 16.99375, 17.1, 17.202083333333334, 17.258333333333333, 17.3125, 17.375, 17.375, 17.434722222222224, 17.472916666666666, 17.502083333333335, 17.56388888888889, 17.57777777777778, 17.625, 17.68611111111111, 17.75, 17.7625, 17.780555555555555, 17.791666666666668, 17.846527777777776, 17.854861111111113, 18.0, 18.17361111111111, 18.291666666666668, 18.354166666666668, 18.37013888888889, 18.564583333333335, 18.568055555555556, 18.573611111111113, 18.618055555555557, 18.677777777777777, 18.680555555555557, 18.825694444444444, 18.875, 18.916666666666668, 18.92013888888889, 18.92013888888889, 18.920833333333334, 18.958333333333332, 18.960416666666667, 19.0, 19.0, 19.010416666666668, 19.060416666666665, 19.129166666666666, 19.147916666666667, 19.333333333333332, 19.54375, 19.57847222222222, 19.645138888888887, 19.71875, 19.76597222222222, 19.784027777777776, 19.791666666666668, 19.832638888888887, 19.884027777777778, 19.931944444444444, 20.0, 20.260416666666668, 20.37986111111111, 20.395833333333332, 20.404166666666665, 20.528472222222224, 20.541666666666668, 20.5625, 20.62361111111111, 20.625, 20.707638888888887, 20.738194444444446, 20.872916666666665, 20.94097222222222, 20.959027777777777, 20.98125, 21.0, 21.006944444444443, 21.04652777777778, 21.0625, 21.2875, 21.30902777777778, 21.434722222222224, 21.486805555555556, 21.510416666666668, 21.538194444444443, 21.540972222222223, 21.583333333333332, 21.585416666666667, 21.586805555555557, 21.59861111111111, 21.693055555555556, 21.694444444444443, 21.70138888888889, 21.720833333333335, 21.79861111111111, 21.925, 22.020833333333332, 22.314583333333335, 22.433333333333334, 22.52777777777778, 22.575, 22.668055555555554, 22.825, 22.864583333333332, 22.913194444444443, 22.94097222222222, 22.958333333333332, 23.0, 23.0, 23.03472222222222, 23.23472222222222, 23.40138888888889, 23.422916666666666, 23.489583333333332, 23.520833333333332, 23.554861111111112, 23.583333333333332, 23.63888888888889, 23.646527777777777, 23.677083333333332, 23.708333333333332, 23.708333333333332, 23.728472222222223, 23.745833333333334, 23.75, 23.7625, 23.778472222222224, 23.84722222222222, 23.85972222222222, 23.85972222222222, 24.0, 24.0, 24.019444444444446, 24.125, 24.291666666666668, 24.322222222222223, 24.350694444444443, 24.384027777777778, 24.591666666666665, 24.76527777777778, 24.78472222222222, 24.791666666666668, 24.791666666666668, 24.8, 24.875, 24.89236111111111, 25.084027777777777, 25.273611111111112, 25.413888888888888, 25.427083333333332, 25.625, 25.650694444444444, 25.794444444444444, 25.8125, 25.92152777777778, 25.958333333333332, 26.0, 26.0, 26.229166666666668, 26.490972222222222, 26.5375, 26.585416666666667, 26.600694444444443, 26.700694444444444, 26.75, 26.82986111111111, 26.852777777777778, 26.874305555555555, 26.889583333333334, 26.895833333333332, 26.90763888888889, 27.0, 27.0, 27.01597222222222, 27.041666666666668, 27.049305555555556, 27.09236111111111, 27.270833333333332, 27.458333333333332, 27.459722222222222, 27.597916666666666, 27.68402777777778, 27.69375, 27.704166666666666, 27.704166666666666, 27.759722222222223, 27.775, 27.801388888888887, 27.81111111111111, 27.833333333333332, 27.836805555555557, 27.836805555555557, 27.84027777777778, 27.852083333333333, 27.864583333333332, 28.25, 28.291666666666668, 28.3125, 28.375, 28.375, 28.4375, 28.476388888888888, 28.490277777777777, 28.666666666666668, 28.68402777777778, 28.69236111111111, 28.71875, 28.74513888888889, 28.75, 28.756944444444443, 28.799305555555556, 28.872222222222224, 28.875, 28.9, 29.038194444444443, 29.113194444444446, 29.11875, 29.288194444444443, 29.30763888888889, 29.333333333333332, 29.375, 29.520833333333332, 29.541666666666668, 29.541666666666668, 29.68611111111111, 29.836805555555557, 29.854166666666668, 29.882638888888888, 29.913888888888888, 29.916666666666668, 29.916666666666668, 30.0, 30.0, 30.309722222222224, 30.332638888888887, 30.38125, 30.40763888888889, 30.42222222222222, 30.475694444444443, 30.584722222222222, 30.604166666666668, 30.610416666666666, 30.625, 30.666666666666668, 30.666666666666668, 30.68611111111111, 30.70486111111111, 30.708333333333332, 30.71527777777778, 30.754166666666666, 30.773611111111112, 30.825694444444444, 30.86111111111111, 30.864583333333332, 30.886805555555554, 30.945138888888888, 31.0, 31.0, 31.0, 31.385416666666668, 31.429861111111112, 31.50138888888889, 31.566666666666666, 31.604166666666668, 31.61111111111111, 31.677777777777777, 31.68263888888889, 31.729166666666668, 31.74375, 31.839583333333334, 31.854166666666668, 31.913194444444443, 31.913888888888888, 31.934722222222224, 31.940277777777776, 31.947222222222223, 31.96527777777778, 32.0, 32.0, 32.10138888888889, 32.33263888888889, 32.354166666666664, 32.458333333333336, 32.479166666666664, 32.614583333333336, 32.68541666666667, 32.697916666666664, 32.71666666666667, 32.74583333333333, 32.74861111111111, 32.75, 32.81666666666667, 32.821527777777774, 32.954166666666666, 33.0, 33.0, 33.0, 33.0, 33.13472222222222, 33.375, 33.446527777777774, 33.46944444444444, 33.49166666666667, 33.52916666666667, 33.545138888888886, 33.65833333333333, 33.69513888888889, 33.735416666666666, 33.78402777777778, 33.80555555555556, 33.855555555555554, 33.884027777777774, 33.90625, 33.90763888888889, 34.0, 34.30277777777778, 34.31666666666667, 34.329166666666666, 34.333333333333336, 34.39375, 34.46458333333333, 34.49722222222222, 34.50625, 34.572916666666664, 34.577777777777776, 34.580555555555556, 34.58263888888889, 34.672222222222224, 34.677083333333336, 34.77291666666667, 34.77986111111111, 34.829861111111114, 34.88333333333333, 35.0, 35.0, 35.0, 35.0, 35.0, 35.0, 35.37708333333333, 35.385416666666664, 35.46875, 35.55694444444445, 35.641666666666666, 35.666666666666664, 35.69375, 35.71041666666667, 35.71875, 35.72152777777778, 35.85138888888889, 35.892361111111114, 35.915277777777774, 36.0, 36.0, 36.0, 36.0, 36.10138888888889, 36.21597222222222, 36.30972222222222, 36.325, 36.33263888888889, 36.41597222222222, 36.428472222222226, 36.479166666666664, 36.484722222222224, 36.52916666666667, 36.577083333333334, 36.607638888888886, 36.613194444444446, 36.63055555555555, 36.642361111111114, 36.68680555555556, 36.708333333333336, 36.71388888888889, 36.71944444444444, 36.75, 36.763888888888886, 36.824305555555554, 36.885416666666664, 36.90763888888889, 36.922222222222224, 37.0, 37.43055555555556, 37.43055555555556, 37.43472222222222, 37.455555555555556, 37.48125, 37.5, 37.54236111111111, 37.544444444444444, 37.625, 37.638194444444444, 37.6625, 37.71875, 37.732638888888886, 37.79097222222222, 37.861111111111114, 37.86805555555556, 37.94444444444444, 38.0, 38.395833333333336, 38.40625, 38.4125, 38.458333333333336, 38.47083333333333, 38.4875, 38.50069444444444, 38.50416666666667, 38.516666666666666, 38.517361111111114, 38.54375, 38.55625, 38.6125, 38.645833333333336, 38.65694444444444, 38.708333333333336, 38.709722222222226, 38.75, 38.763194444444444, 38.8125, 38.82361111111111, 38.83680555555556, 38.90069444444445, 38.959722222222226, 39.08819444444445, 39.11805555555556, 39.11875, 39.12291666666667, 39.30763888888889, 39.50763888888889, 39.518055555555556, 39.522222222222226, 39.545138888888886, 39.56527777777778, 39.71180555555556, 39.74722222222222, 39.77916666666667, 39.833333333333336, 39.85069444444444, 39.85069444444444, 39.86944444444445, 39.875, 39.885416666666664, 39.895833333333336, 39.916666666666664, 39.9375, 40.19444444444444, 40.2, 40.333333333333336, 40.479166666666664, 40.49444444444445, 40.56458333333333, 40.61527777777778, 40.678472222222226, 40.84375, 40.90902777777778, 41.0, 41.011805555555554, 41.020833333333336, 41.04375, 41.050694444444446, 41.175, 41.18958333333333, 41.21111111111111, 41.27638888888889, 41.36388888888889, 41.37152777777778, 41.42638888888889, 41.47222222222222, 41.47430555555555, 41.511805555555554, 41.53819444444444, 41.541666666666664, 41.541666666666664, 41.56944444444444, 41.604166666666664, 41.625, 41.62638888888889, 41.63611111111111, 41.65763888888889, 41.665277777777774, 41.708333333333336, 41.72083333333333, 41.7625, 41.765277777777776, 41.770833333333336, 41.80555555555556, 41.831944444444446, 41.88125, 41.885416666666664, 41.99444444444445, 42.0, 42.12569444444444, 42.375, 42.47291666666667, 42.489583333333336, 42.52291666666667, 42.52430555555556, 42.56527777777778, 42.62083333333333, 42.66041666666667, 42.666666666666664, 42.731944444444444, 42.736111111111114, 42.75, 42.77291666666667, 42.791666666666664, 42.889583333333334, 42.99652777777778, 42.99652777777778, 43.0, 43.294444444444444, 43.39652777777778, 43.397222222222226, 43.418055555555554, 43.458333333333336, 43.583333333333336, 43.62430555555556, 43.625, 43.666666666666664, 43.761805555555554, 43.765277777777776, 43.87152777777778, 43.954861111111114, 44.0, 44.0, 44.0, 44.02847222222222, 44.291666666666664, 44.325694444444444, 44.329166666666666, 44.34375, 44.510416666666664, 44.53125, 44.53819444444444, 44.579861111111114, 44.59097222222222, 44.65763888888889, 44.677083333333336, 44.68888888888889, 44.69444444444444, 44.697916666666664, 44.75277777777778, 44.7625, 44.77152777777778, 44.79375, 44.81180555555556, 44.82083333333333, 44.825, 44.858333333333334, 44.86805555555556, 44.91111111111111, 45.0, 45.0, 45.14791666666667, 45.375, 45.40763888888889, 45.46875, 45.479166666666664, 45.49513888888889, 45.56805555555555, 45.583333333333336, 45.64375, 45.65069444444445, 45.6625, 45.670833333333334, 45.674305555555556, 45.69027777777778, 45.703472222222224, 45.72013888888889, 45.72152777777778, 45.72430555555555, 45.74236111111111, 45.798611111111114, 45.81527777777778, 45.854166666666664, 46.0, 46.0, 46.0, 46.0, 46.18541666666667, 46.19027777777778, 46.33888888888889, 46.34583333333333, 46.416666666666664, 46.42986111111111, 46.70763888888889, 46.75, 46.77847222222222, 46.915277777777774, 47.00416666666667, 47.00416666666667, 47.08263888888889, 47.12569444444444, 47.12777777777778, 47.19027777777778, 47.40694444444444, 47.416666666666664, 47.46458333333333, 47.48125, 47.49652777777778, 47.547222222222224, 47.55486111111111, 47.669444444444444, 47.72152777777778, 47.87361111111111, 47.9375, 48.020833333333336, 48.03541666666667, 48.16041666666667, 48.31041666666667, 48.3125, 48.357638888888886, 48.40902777777778, 48.5, 48.5625, 48.5875, 48.62430555555556, 48.644444444444446, 48.65625, 48.697916666666664, 48.72638888888889, 48.75069444444444, 48.75486111111111, 48.763194444444444, 48.770833333333336, 48.8125, 48.84375, 48.875, 49.0, 49.145833333333336, 49.25277777777778, 49.360416666666666, 49.39861111111111, 49.518055555555556, 49.55555555555556, 49.5625, 49.61805555555556, 49.67638888888889, 49.68958333333333, 49.69722222222222, 49.71458333333333, 49.78611111111111, 49.793055555555554, 49.81597222222222, 49.864583333333336, 49.86805555555556, 49.889583333333334, 49.895833333333336, 49.954166666666666, 50.0, 50.00208333333333, 50.03402777777778, 50.32083333333333, 50.329861111111114, 50.34097222222222, 50.47708333333333, 50.49166666666667, 50.515972222222224, 50.520833333333336, 50.56111111111111, 50.56527777777778, 50.614583333333336, 50.666666666666664, 50.671527777777776, 50.677083333333336, 50.69027777777778, 50.69375, 50.70902777777778, 50.76111111111111, 50.763888888888886, 50.791666666666664, 50.825, 50.834722222222226, 50.96458333333333, 51.0, 51.360416666666666, 51.388888888888886, 51.390972222222224, 51.41388888888889, 51.43611111111111, 51.50763888888889, 51.59375, 51.607638888888886, 51.61736111111111, 51.63055555555555, 51.7375, 51.80416666666667, 52.0, 52.291666666666664, 52.291666666666664, 52.328472222222224, 52.33541666666667, 52.40277777777778, 52.43888888888889, 52.455555555555556, 52.53611111111111, 52.575694444444444, 52.68194444444445, 52.68888888888889, 52.824305555555554, 52.827083333333334, 52.90208333333333, 53.22986111111111, 53.239583333333336, 53.37013888888889, 53.520833333333336, 53.575694444444444, 53.625, 53.645833333333336, 53.69375, 53.72986111111111, 53.75, 53.75, 53.77569444444445, 53.863194444444446, 53.9375, 53.950694444444444, 54.0, 54.0, 54.00972222222222, 54.09722222222222, 54.32222222222222, 54.34930555555555, 54.37569444444444, 54.49930555555556, 54.65208333333333, 54.697916666666664, 54.70625, 54.71597222222222, 54.738194444444446, 54.74375, 54.83680555555556, 54.875, 54.93055555555556, 54.986111111111114, 55.00069444444444, 55.047916666666666, 55.229166666666664, 55.354166666666664, 55.357638888888886, 55.4125, 55.43194444444445, 55.547222222222224, 55.74236111111111, 55.75, 55.75833333333333, 55.768055555555556, 55.78333333333333, 55.824305555555554, 55.830555555555556, 55.86666666666667, 55.922222222222224, 56.06805555555555, 56.170138888888886, 56.24722222222222, 56.355555555555554, 56.375, 56.46458333333333, 56.52291666666667, 56.543055555555554, 56.59791666666667, 56.60069444444444, 56.62986111111111, 56.638888888888886, 56.669444444444444, 56.697916666666664, 56.72222222222222, 56.729166666666664, 56.74652777777778, 56.78611111111111, 56.80902777777778, 56.833333333333336, 56.86805555555556, 56.90069444444445, 56.90972222222222, 56.958333333333336, 57.0, 57.0, 57.01875, 57.35138888888889, 57.44722222222222, 57.50138888888889, 57.540277777777774, 57.55625, 57.574305555555554, 57.61805555555556, 57.65625, 57.68680555555556, 57.71875, 57.80625, 57.84305555555556, 57.84375, 57.84513888888889, 57.94166666666667, 57.94166666666667, 57.96805555555556, 57.990972222222226, 58.0, 58.09930555555555, 58.201388888888886, 58.27291666666667, 58.28541666666667, 58.5, 58.68125, 58.6875, 58.704861111111114, 58.71527777777778, 58.764583333333334, 58.796527777777776, 58.895833333333336, 59.0, 59.02361111111111, 59.02569444444445, 59.108333333333334, 59.225, 59.38263888888889, 59.451388888888886, 59.475, 59.479166666666664, 59.510416666666664, 59.52777777777778, 59.52847222222222, 59.583333333333336, 59.62152777777778, 59.63055555555555, 59.69861111111111, 59.7375, 59.739583333333336, 59.75, 59.833333333333336, 59.84236111111111, 59.91041666666667, 59.927083333333336, 59.94861111111111, 59.986111111111114, 60.0, 60.02777777777778, 60.25, 60.33888888888889, 60.391666666666666, 60.57013888888889, 60.58819444444445, 60.640277777777776, 60.645833333333336, 60.69097222222222, 60.708333333333336, 60.75, 60.770833333333336, 60.77361111111111, 60.85625, 60.864583333333336, 60.87916666666667, 60.94097222222222, 60.95902777777778, 60.979166666666664, 61.0, 61.0, 61.00555555555555, 61.10208333333333, 61.263888888888886, 61.416666666666664, 61.49166666666667, 61.49861111111111, 61.541666666666664, 61.55902777777778, 61.56736111111111, 61.608333333333334, 61.666666666666664, 61.666666666666664, 61.675694444444446, 61.69097222222222, 61.72430555555555, 61.72569444444444, 61.74791666666667, 61.82013888888889, 61.834722222222226, 61.947916666666664, 62.0, 62.291666666666664, 62.333333333333336, 62.41111111111111, 62.57222222222222, 62.59722222222222, 62.6041666

In [ ]:
data_rox = nested_list[3]
data_mat = nested_list[4]

In [ ]:
print(data_mat)
np.max(data_mat)

[0.0, 0.0, 0.10416666666666667, 0.11388888888888889, 0.3958333333333333, 0.40625, 0.4152777777777778, 0.5388888888888889, 0.5527777777777778, 0.7277777777777777, 0.7479166666666667, 0.7493055555555556, 0.7722222222222223, 0.7888888888888889, 1.0173611111111112, 1.0625, 1.24375, 1.3125, 1.4826388888888888, 1.5020833333333334, 1.5347222222222223, 1.6041666666666667, 1.6284722222222223, 1.6381944444444445, 1.6979166666666667, 1.7013888888888888, 1.7409722222222221, 1.7791666666666666, 1.8041666666666667, 1.8375, 1.9034722222222222, 2.0, 2.1, 2.25, 2.390277777777778, 2.5083333333333333, 2.6486111111111112, 2.6875, 2.7041666666666666, 2.8541666666666665, 2.8777777777777778, 2.910416666666667, 2.9694444444444446, 3.0, 3.0, 3.310416666666667, 3.3368055555555554, 3.3645833333333335, 3.3680555555555554, 3.4875, 3.4881944444444444, 3.5, 3.6347222222222224, 3.6625, 3.6930555555555555, 3.7125, 3.73125, 3.7930555555555556, 3.879166666666667, 3.9430555555555555, 4.0, 4.0, 4.0625, 4.272222222222222, 4.375, 4.5, 4.520833333333333, 4.6097222222222225, 4.71875, 4.980555555555555, 5.0, 5.0, 5.0, 5.043055555555555, 5.131944444444445, 5.279166666666667, 5.447916666666667, 5.554861111111111, 5.611111111111111, 5.629861111111111, 5.852083333333334, 5.9631944444444445, 6.0, 6.003472222222222, 6.1875, 6.211805555555555, 6.305555555555555, 6.365972222222222, 6.475694444444445, 6.575, 6.59375, 6.7625, 6.902777777777778, 6.958333333333333, 7.0, 7.0, 7.184722222222222, 7.192361111111111, 7.288888888888889, 7.322916666666667, 7.322916666666667, 7.397222222222222, 7.475694444444445, 7.479166666666667, 7.481944444444444, 7.488888888888889, 7.517361111111111, 7.677083333333333, 7.736111111111111, 7.885416666666667, 8.0, 8.0, 8.416666666666666, 8.444444444444445, 8.477083333333333, 8.520833333333334, 8.540972222222223, 8.643055555555556, 8.666666666666666, 8.668055555555556, 8.679166666666667, 8.683333333333334, 8.731944444444444, 8.76388888888889, 8.833333333333334, 8.899305555555555, 8.905555555555555, 8.984722222222222, 9.0, 9.0, 9.380555555555556, 9.46875, 9.506944444444445, 9.525, 9.691666666666666, 9.708333333333334, 9.710416666666667, 9.729166666666666, 9.785416666666666, 9.833333333333334, 9.833333333333334, 9.854166666666666, 9.905555555555555, 9.978472222222223, 9.979166666666666, 10.264583333333333, 10.375, 10.375, 10.402777777777779, 10.41388888888889, 10.416666666666666, 10.479861111111111, 10.496527777777779, 10.541666666666666, 10.67986111111111, 10.685416666666667, 10.6875, 10.827083333333333, 10.82986111111111, 10.875, 10.8875, 10.917361111111111, 11.0, 11.340277777777779, 11.344444444444445, 11.472222222222221, 11.5, 11.51875, 11.559027777777779, 11.622916666666667, 11.636805555555556, 11.676388888888889, 11.67986111111111, 11.708333333333334, 11.717361111111112, 11.741666666666667, 11.786805555555556, 11.789583333333333, 11.852777777777778, 12.2375, 12.46111111111111, 12.51736111111111, 12.66875, 12.80625, 12.847916666666666, 13.0, 13.265972222222222, 13.284722222222221, 13.322916666666666, 13.323611111111111, 13.375, 13.458333333333334, 13.474305555555556, 13.541666666666666, 13.541666666666666, 13.591666666666667, 13.60625, 13.727777777777778, 13.775694444444444, 13.792361111111111, 13.831944444444444, 13.855555555555556, 13.967361111111112, 14.063888888888888, 14.329166666666667, 14.426388888888889, 14.4375, 14.4375, 14.473611111111111, 14.515972222222222, 14.540972222222223, 14.595138888888888, 14.623611111111112, 14.63888888888889, 14.666666666666666, 14.697916666666666, 14.7625, 14.881944444444445, 15.0, 15.0, 15.0, 15.13888888888889, 15.295833333333333, 15.340277777777779, 15.397916666666667, 15.436111111111112, 15.4375, 15.440972222222221, 15.5, 15.5, 15.695833333333333, 15.715972222222222, 15.718055555555555, 15.74375, 15.75, 15.833333333333334, 15.852083333333333, 15.91875, 15.934722222222222, 15.989583333333334, 16.021527777777777, 16.416666666666668, 16.427083333333332, 16.430555555555557, 16.44236111111111, 16.5, 16.73263888888889, 16.74861111111111, 16.770833333333332, 16.935416666666665, 17.019444444444446, 17.180555555555557, 17.364583333333332, 17.370833333333334, 17.375, 17.489583333333332, 17.541666666666668, 17.5625, 17.59375, 17.65277777777778, 17.665277777777778, 17.790277777777778, 17.791666666666668, 17.808333333333334, 17.82777777777778, 17.85625, 17.865277777777777, 17.93611111111111, 18.0, 18.0, 18.0, 18.0, 18.07638888888889, 18.09722222222222, 18.153472222222224, 18.333333333333332, 18.600694444444443, 18.708333333333332, 18.739583333333332, 18.744444444444444, 18.775, 18.803472222222222, 18.866666666666667, 18.976388888888888, 19.02777777777778, 19.034027777777776, 19.52777777777778, 19.590972222222224, 19.591666666666665, 19.615972222222222, 19.680555555555557, 19.73402777777778, 19.759027777777778, 19.76388888888889, 19.83125, 20.13888888888889, 20.13888888888889, 20.13888888888889, 20.13888888888889, 20.13888888888889, 20.13888888888889, 20.13888888888889, 20.13888888888889, 20.13888888888889, 20.302777777777777, 20.382638888888888, 20.399305555555557, 20.474305555555556, 20.480555555555554, 20.541666666666668, 20.665277777777778, 20.705555555555556, 20.708333333333332, 20.725694444444443, 20.756944444444443, 20.797916666666666, 20.8125, 20.813194444444445, 20.875, 20.906944444444445, 20.93888888888889, 21.0125, 21.416666666666668, 21.614583333333332, 21.614583333333332, 21.770138888888887, 21.802083333333332, 21.802083333333332, 21.905555555555555, 22.03611111111111, 22.0625, 22.375, 22.479166666666668, 22.67361111111111, 22.698611111111113, 22.708333333333332, 22.794444444444444, 22.806944444444444, 22.875, 23.073611111111113, 23.35763888888889, 23.358333333333334, 23.384027777777778, 23.41875, 23.46388888888889, 23.46875, 23.5, 23.68263888888889, 23.727083333333333, 23.736805555555556, 23.768055555555556, 23.811805555555555, 24.0, 24.0, 24.064583333333335, 24.29652777777778, 24.333333333333332, 24.429861111111112, 24.46527777777778, 24.617361111111112, 24.676388888888887, 24.689583333333335, 24.699305555555554, 24.729166666666668, 24.76388888888889, 24.770833333333332, 24.791666666666668, 24.791666666666668, 24.847916666666666, 24.897222222222222, 24.947916666666668, 24.990972222222222, 25.052083333333332, 25.291666666666668, 25.419444444444444, 25.4375, 25.518055555555556, 25.565277777777776, 25.586111111111112, 25.635416666666668, 25.71527777777778, 25.716666666666665, 25.75, 25.757638888888888, 25.76388888888889, 25.855555555555554, 25.875, 25.87847222222222, 25.88888888888889, 25.9375, 25.947916666666668, 25.95277777777778, 26.155555555555555, 26.206944444444446, 26.275694444444444, 26.375694444444445, 26.395138888888887, 26.47222222222222, 26.510416666666668, 26.695833333333333, 26.75, 26.833333333333332, 26.908333333333335, 27.0, 27.03472222222222, 27.05902777777778, 27.30902777777778, 27.450694444444444, 27.50347222222222, 27.569444444444443, 27.595833333333335, 27.68125, 27.684722222222224, 27.720833333333335, 27.743055555555557, 27.867361111111112, 27.89027777777778, 27.969444444444445, 28.0, 28.0, 28.070138888888888, 28.093055555555555, 28.09722222222222, 28.129166666666666, 28.3625, 28.42013888888889, 28.458333333333332, 28.47013888888889, 28.49513888888889, 28.509722222222223, 28.549305555555556, 28.550694444444446, 28.632638888888888, 28.65625, 28.677777777777777, 28.6875, 28.72361111111111, 28.75347222222222, 28.759027777777778, 28.789583333333333, 28.794444444444444, 28.841666666666665, 28.84861111111111, 28.90972222222222, 28.93263888888889, 28.975694444444443, 29.0, 29.074305555555554, 29.12638888888889, 29.43888888888889, 29.48263888888889, 29.524305555555557, 29.555555555555557, 29.665277777777778, 29.727083333333333, 29.74652777777778, 29.81111111111111, 29.980555555555554, 30.0, 30.0, 30.025, 30.256944444444443, 30.27777777777778, 30.304166666666667, 30.322916666666668, 30.38888888888889, 30.42013888888889, 30.520833333333332, 30.5375, 30.566666666666666, 30.572222222222223, 30.666666666666668, 30.668055555555554, 30.675694444444446, 30.74375, 30.747916666666665, 30.76527777777778, 30.802083333333332, 30.87361111111111, 31.0, 31.075694444444444, 31.209722222222222, 31.291666666666668, 31.34722222222222, 31.34861111111111, 31.40625, 31.416666666666668, 31.426388888888887, 31.426388888888887, 31.529166666666665, 31.5625, 31.59861111111111, 31.64027777777778, 31.72361111111111, 31.780555555555555, 31.78472222222222, 31.829166666666666, 31.838194444444444, 31.84236111111111, 31.846527777777776, 31.856944444444444, 31.867361111111112, 32.32222222222222, 32.34652777777778, 32.375, 32.420138888888886, 32.451388888888886, 32.520833333333336, 32.541666666666664, 32.583333333333336, 32.71111111111111, 32.890972222222224, 33.025, 33.09513888888889, 33.09861111111111, 33.34722222222222, 33.36666666666667, 33.427083333333336, 33.42986111111111, 33.606944444444444, 33.608333333333334, 33.68333333333333, 33.708333333333336, 33.85486111111111, 33.951388888888886, 34.270833333333336, 34.33263888888889, 34.36805555555556, 34.41736111111111, 34.60625, 34.68472222222222, 34.733333333333334, 34.734027777777776, 34.802083333333336, 34.864583333333336, 34.87916666666667, 34.916666666666664, 35.0, 35.0, 35.43055555555556, 35.4625, 35.5, 35.548611111111114, 35.577083333333334, 35.59791666666667, 35.61666666666667, 35.69444444444444, 35.72847222222222, 35.74236111111111, 35.765277777777776, 35.802083333333336, 35.893055555555556, 36.41111111111111, 36.4125, 36.50625, 36.53333333333333, 36.53888888888889, 36.65694444444444, 36.678472222222226, 36.696527777777774, 36.72291666666667, 36.734027777777776, 36.74513888888889, 36.74652777777778, 36.825694444444444, 36.8375, 36.83819444444445, 36.86944444444445, 36.87847222222222, 36.895833333333336, 37.357638888888886, 37.5, 37.56388888888889, 37.575, 37.6375, 37.75208333333333, 37.75416666666667, 37.85347222222222, 38.0, 38.0, 38.083333333333336, 38.15069444444445, 38.24444444444445, 38.28333333333333, 38.375, 38.375, 38.541666666666664, 38.604166666666664, 38.61944444444445, 38.732638888888886, 38.9625, 39.0, 39.03680555555555, 39.18055555555556, 39.333333333333336, 39.416666666666664, 39.47638888888889, 39.485416666666666, 39.50833333333333, 39.62847222222222, 39.62916666666667, 39.71180555555556, 39.735416666666666, 39.766666666666666, 39.81388888888889, 39.94375, 40.0, 40.019444444444446, 40.09166666666667, 40.09236111111111, 40.21041666666667, 40.23125, 40.30138888888889, 40.325, 40.333333333333336, 40.36805555555556, 40.549305555555556, 40.602777777777774, 40.61944444444445, 40.641666666666666, 40.697916666666664, 40.725, 40.75347222222222, 40.828472222222224, 40.87152777777778, 40.88125, 40.9, 40.916666666666664, 40.99583333333333, 41.0, 41.09375, 41.33819444444445, 41.4125, 41.44444444444444, 41.447916666666664, 41.57361111111111, 41.607638888888886, 41.62291666666667, 41.69513888888889, 41.69583333333333, 41.703472222222224, 41.738194444444446, 41.760416666666664, 41.8375, 42.0, 42.079166666666666, 42.11805555555556, 42.31527777777778, 42.354166666666664, 42.36805555555556, 42.4375, 42.489583333333336, 42.49861111111111, 42.53819444444444, 42.541666666666664, 42.72013888888889, 42.82361111111111, 42.84791666666667, 42.875, 43.0, 43.290277777777774, 43.333333333333336, 43.61875, 43.763888888888886, 43.794444444444444, 43.93402777777778, 43.95763888888889, 44.324305555555554, 44.41597222222222, 44.479166666666664, 44.49722222222222, 44.625, 44.705555555555556, 44.72708333333333, 44.75, 44.87013888888889, 44.88333333333333, 45.0, 45.0, 45.0, 45.33402777777778, 45.39861111111111, 45.50277777777778, 45.584722222222226, 45.666666666666664, 45.71597222222222, 45.767361111111114, 45.77152777777778, 45.833333333333336, 45.833333333333336, 45.83402777777778, 45.86805555555556, 45.88333333333333, 45.90972222222222, 45.979166666666664, 46.025, 46.03333333333333, 46.41875, 46.52569444444445, 46.604166666666664, 46.611805555555556, 46.62083333333333, 46.666666666666664, 46.791666666666664, 46.791666666666664, 46.93125, 46.952777777777776, 46.953472222222224, 46.99236111111111, 47.0, 47.0, 47.09722222222222, 47.145833333333336, 47.15277777777778, 47.422916666666666, 47.65902777777778, 47.708333333333336, 47.71527777777778, 47.74652777777778, 47.75555555555555, 47.791666666666664, 47.795138888888886, 47.797916666666666, 47.861111111111114, 47.88263888888889, 48.0625, 48.071527777777774, 48.352777777777774, 48.364583333333336, 48.38472222222222, 48.46527777777778, 48.518055555555556, 48.604166666666664, 48.666666666666664, 48.770833333333336, 48.79375, 48.798611111111114, 48.827777777777776, 48.92986111111111, 49.0, 49.25416666666667, 49.36805555555556, 49.385416666666664, 49.44861111111111, 49.46388888888889, 49.479166666666664, 49.541666666666664, 49.541666666666664, 49.62152777777778, 49.62569444444444, 49.63472222222222, 49.6875, 49.700694444444444, 49.702777777777776, 49.71111111111111, 49.732638888888886, 49.75694444444444, 49.87569444444444, 49.9375, 50.07361111111111, 50.33263888888889, 50.354166666666664, 50.416666666666664, 50.427083333333336, 50.44027777777778, 50.5625, 50.59861111111111, 50.65763888888889, 51.0, 51.06111111111111, 51.33819444444445, 51.39861111111111, 51.481944444444444, 51.541666666666664, 51.583333333333336, 51.615972222222226, 51.6375, 51.645833333333336, 51.71388888888889, 51.88333333333333, 52.0, 52.0, 52.020833333333336, 52.020833333333336, 52.025, 52.079861111111114, 52.24166666666667, 52.37430555555556, 52.449305555555554, 52.458333333333336, 52.46527777777778, 52.486111111111114, 52.60625, 52.62152777777778, 52.65347222222222, 52.833333333333336, 52.919444444444444, 52.94375, 53.045138888888886, 53.076388888888886, 53.31944444444444, 53.55763888888889, 53.59236111111111, 53.68958333333333, 53.87083333333333, 53.90694444444444, 54.0, 54.10069444444444, 54.11388888888889, 54.22222222222222, 54.27638888888889, 54.40625, 54.425694444444446, 54.43958333333333, 54.50277777777778, 54.513194444444444, 54.525, 54.5375, 54.72847222222222, 54.75486111111111, 54.81666666666667, 54.86944444444445, 54.9, 54.92777777777778, 55.0, 55.0, 55.10208333333333, 55.25347222222222, 55.477777777777774, 55.49791666666667, 55.49930555555556, 55.50555555555555, 55.60347222222222, 55.615972222222226, 55.69236111111111, 55.706944444444446, 55.708333333333336, 55.75694444444444, 55.77361111111111, 55.80833333333333, 55.81527777777778, 55.958333333333336, 56.0, 56.0, 56.49513888888889, 56.53541666666667, 56.638194444444444, 56.65972222222222, 56.703472222222224, 56.90208333333333, 56.93958333333333, 56.958333333333336, 57.0, 57.0, 57.02291666666667, 57.03958333333333, 57.10625, 57.291666666666664, 57.42777777777778, 57.5375, 57.604166666666664, 57.61388888888889, 57.645833333333336, 58.270833333333336, 58.390277777777776, 58.416666666666664, 58.56319444444444, 58.59166666666667, 58.62013888888889, 58.639583333333334, 58.671527777777776, 58.68333333333333, 58.69444444444444, 58.708333333333336, 58.708333333333336, 58.71875, 58.83402777777778, 58.854166666666664, 58.864583333333336, 58.90902777777778, 58.988194444444446, 59.15625, 59.166666666666664, 59.25, 59.40763888888889, 59.44375, 59.479166666666664, 59.53194444444444, 59.53472222222222, 59.56041666666667, 59.5625, 59.71388888888889, 59.7375, 59.74583333333333, 59.75486111111111, 59.77638888888889, 59.92916666666667, 59.9875, 60.0, 60.0, 60.34722222222222, 60.611111111111114, 60.678472222222226, 60.69722222222222, 60.775, 60.80486111111111, 60.80694444444445, 61.0, 61.0, 61.200694444444444, 61.264583333333334, 61.391666666666666, 61.43472222222222, 61.52430555555556, 61.543055555555554, 61.547916666666666, 61.736805555555556, 61.81458333333333, 61.833333333333336, 61.90694444444444, 61.97847222222222, 62.0, 62.016666666666666, 62.333333333333336, 62.46597222222222, 62.52291666666667, 62.614583333333336, 62.71180555555556, 62.72430555555555, 62.730555555555554, 62.75208333333333, 62.775, 62.825, 62.83125, 62.96875, 63.020833333333336, 63.03472222222222, 63.31944444444444, 63.34027777777778, 63.40069444444445, 63.49583333333333, 63.53472222222222, 63.62986111111111, 63.63194444444444, 63.75138888888889, 63.8125, 63.828472222222224, 63.84097222222222, 63.84236111111111, 63.92638888888889, 63.93055555555556, 63.97708333333333, 64.0, 64.31736111111111, 64.35625, 64.36041666666667, 64.36666666666666, 64.38194444444444, 64.38263888888889, 64.42013888888889, 64.46319444444444, 64.47430555555556, 64.48472222222222, 64.6048611111111, 64.60833333333333, 64.63888888888889, 64.64583333333333, 64.64652777777778, 64.81111111111112, 65.07986111111111, 65.14375, 65.16458333333334, 65.28958333333334, 65.35625, 65.36319444444445, 65.45833333333333, 65.46805555555555, 65.54791666666667, 65.60625, 65.64861111111111, 65.75555555555556, 65.75763888888889, 65.78611111111111, 65.81805555555556, 65.92708333333333, 65.97361111111111, 65.99791666666667, 65.99861111111112, 66.02083333333333, 66.03611111111111, 66.31944444444444, 66.39305555555555, 66.4, 66.44097222222223, 66.50138888888888, 66.50694444444444, 66.52291666666666, 66.54027777777777, 66.5513888888889, 66.60625, 66.67430555555555, 66.71111111111111, 66.71180555555556, 66.74097222222223, 66.76388888888889, 66.77638888888889, 66.81736111111111, 66.97847222222222, 67.0, 67.00833333333334, 67.04097222222222, 67.20694444444445, 67.33333333333333, 67.45555555555555, 67.48680555555555, 67.62777777777778, 67.67291666666667, 67.74930555555555, 67.75, 68.0, 68.02083333333333, 68.07291666666667, 68.15069444444444, 68.40138888888889, 68.41319444444444, 68.54166666666667, 68.58333333333333, 68.66666666666667, 68.71736111111112, 68.75555555555556, 68.75555555555556, 68.77083333333333, 68.80416666666666, 68.8125, 68.8625, 68.98958333333333, 69.00833333333334, 69.16666666666667, 69.22638888888889, 69.33958333333334, 69.45208333333333, 69.47847222222222, 69.50416666666666, 69.51180555555555, 69.5375, 69.60625, 69.60694444444445, 69.66319444444444, 69.67291666666667, 69.73958333333333, 69.8013888888889, 69.82708333333333, 69.85347222222222, 69.89652777777778, 69.94166666666666, 70.0, 70.05763888888889, 70.27986111111112, 70.36111111111111, 70.36111111111111, 70.39166666666667, 70.39722222222223, 70.4125, 70.50347222222223, 70.51041666666667, 70.62430555555555, 70.64583333333333, 70.64583333333333, 70.64722222222223, 70.7298611111111, 70.73958333333333, 70.75555555555556, 70.82986111111111, 70.90277777777777, 71.3375, 71.36180555555555, 71.38194444444444, 71.41041666666666, 71.43958333333333, 71.5, 71.50833333333334, 71.5625, 71.60416666666667, 71.60416666666667, 71.64236111111111, 71.70347222222222, 71.73055555555555, 71.7375, 71.74861111111112, 71.75625, 71.84930555555556, 71.85694444444445, 71.99444444444444, 72.0, 72.0, 72.0, 72.0, 72.0, 72.0, 72.0, 72.04861111111111, 72.32083333333334, 72.33541666666666, 72.67569444444445, 72.7625, 72.93541666666667, 72.99027777777778, 73.0, 73.06527777777778, 73.3861111111111, 73.4, 73.50555555555556, 73.58680555555556, 73.66666666666667, 73.79166666666667, 73.79444444444445, 73.83958333333334, 73.95833333333333, 74.0, 74.37083333333334, 74.42291666666667, 74.55208333333333, 74.58819444444444, 74.61527777777778, 74.76805555555555, 74.79375, 74.89930555555556, 74.91666666666667, 74.9625, 74.97361111111111, 75.0, 75.01875, 75.05069444444445, 75.13263888888889, 75.26319444444445, 75.33194444444445, 75.51180555555555, 75.56458333333333, 75.56597222222223, 75.60416666666667, 75.65277777777777, 75.72013888888888, 75.75277777777778, 75.75902777777777, 75.76875, 75.90763888888888, 75.95833333333333, 76.21111111111111, 76.27638888888889, 76.325, 76.375, 76.4486111111111, 76.45138888888889, 76.49097222222223, 76.58819444444444, 76.59027777777777, 76.64791666666666, 76.74236111111111, 76.79791666666667, 76.89861111111111, 76.95972222222223, 77.0, 77.24375, 77.29166666666667, 77.37916666666666, 77.45833333333333, 77.52083333333333, 77.56458333333333, 77.63888888888889, 77.68888888888888, 77.99097222222223, 78.0, 78.02083333333333, 78.06180555555555, 78.0625, 78.

np.float64(182.83194444444445)